---
title: "Cessão de Espaço Aquático"
subtitle: "ICMBio"
author: "Luiz Fernando Palin Droubi"
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", out.width = "100%")
library(sf)
```

## Criar objeto

```{r}
# 1. Digitação da Geometria
#  
# Digitar Coordenadas dos vértices
#
# Área Atual
#                       E                 N
atual <- matrix(c(733181.06287287, 7021360.5524924,
                  733158.39741747, 7021477.9827199,
                  733199.90520240, 7021483.3708676, 
                  733248.32043105, 7021414.7298051,
                  733203.65338014, 7021387.8460570,
                  733208.88682840, 7021372.3529161,
                  733181.06287287, 7021360.5524924),
                ncol = 2, byrow = TRUE)
# Mangue
# mangue <- matrix(c(733248.32043105, 7021414.7298051,
#                    733203.65338014, 7021387.8460570,
#                    733208.88682840, 7021372.3529161,
#                    733201.14000000, 7021390.1400000,
#                    733248.32043105, 7021414.7298051),
#                 ncol = 2, byrow = TRUE)
#
# 2. Criação da feição  
#
# Atentar para a definição do crs apropriado
# 
#
# Exemplos:
# WGS 84 = 4326
# SAD 69 22S = 29192
# SIRGAS 2000 22S = 31982
#
pl <- st_sfc(st_polygon(list(atual)))
# pl <- st_sfc(st_multipolygon(
#   list(list(atual), 
#        list(mangue)
#        )
#   )
# )
#
# 3. Criação dos metadados  
#
attr <- data.frame(interessado = "Instituto Chico Mendes de Conservação da Biodiversidade (ICMBio)",
                    cnpj = "04.529.874/0001-91",
                    nup = "04972.002071/2006-12",
                    protocolo = "2081255",
                    ref = 2081279,
                    concedida = TRUE,
                    area = st_area(pl),
                    municipio = 8161,
                    logradouro = "27-00",
                    aval = 85565.73,
                    dataaval = as.Date("22/08/2019", format = "%d/%m/%Y"),
                    refaval = 3645421)
#
# 4. União dos atributos à geometria
#
# Atentar para a definição do crs apropriado
# 
#
# Exemplos:
# WGS 84 = 4326
# SAD 69 22S = 29192
# SIRGAS 2000 22S = 31982
#
spl_df <- st_sf(attr,
                geometry = pl, 
                crs = 31982) %>%
  st_transform(crs = 4326) # Transforma para WGS84.
```

```{r}
spl_df %>%
  leaflet() %>%
  addTiles() %>% 
  addPolygons() %>%
  addPolygons(data = porto_itajai)
```


## Exportar

```{r}
st_write(spl_df, "ICMBio.geojson", delete_dsn = TRUE)
```


